sudo: required
language: generic
services:
  - docker
jobs:
  include:
  - stage: cd
    git:
      depth: 999999
    env: Type='Continuous Deployment'
    script:
      - include/travis/copr-deploy.sh prepare
      - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
stages:
  - name: cd
    if: branch = master AND type = push AND fork = false